### ISSUE TITLE
Template System

### ISSUE THREAD

**Issue by grayghostvisuals** [grayghostvisuals/transformicons#21]
Trying to decide which direction to go in here. I've found a few like [wintersmith](http://wintersmith.io), harp, [Heckle](https://github.com/marijnh/heckle) and [metalsmith](http://www.metalsmith.io). I would rly like to use assemble, but the gulp plugin is apparently not stable until 0.5 of Assemble is released. Maybe @doowb can shed some light on the progress?

**Comment by grayghostvisuals** [comment]
@doowb Where are things at my man?

**Comment by doowb** [comment]
I'll push up an example using `assemble 0.6.0` directly with a gulpfile. I'll probably have that later tonight since I'm at codemash right now..

**Comment by grayghostvisuals** [comment]
@doowb Any chance you can leave me some instructions or quickly getting started pointers so I can give it a go myself?

**Comment by doowb** [comment]
Sure...

Install `assemble 0.6.0`:

```bash
> npm i assemble/assemble#v0.6.0 -D
```

Then use it directly in your `gulpfile.js`

```js
var gulp = require('gulp');
var ext = require('gulp-extname');

var assemble = require('assemble');
assemble.layouts('src/templates/layouts/*.hbs');
assemble.partials('src/templates/partials/*.hbs');
assemble.option('layout', 'default');

gulp.task('default', function () {
  return assemble.src('src/templates/pages/*.hbs')
    .pipe(ext())
    .pipe(assemble.dest('dist/'));
});
```

The `gulp-extname` is used to rename the `.hbs` to `.html` files. It basically contains a mapping of extensions, but you can manually override it by passing in an `ext` option... `.pipe(ext({ext: '.foo'}))`. This is useful if you want to render something differently or your just setting it up for another process.

The assemble API maps to the [template](https://github.com/jonschlinkert/template) API so you can do all of the same things before calling `assemble.src` and `assemble.dest`.

If you have any problems, let me know since it's probably something I can help with quickly.

**Comment by grayghostvisuals** [comment]
Thanks to @doowb we have a wonderful template system to work with. Code should be pushed shortly. Beers all around everyone.

![94393-one-for-my-homies-gif-dr-evil-zksy](https://cloud.githubusercontent.com/assets/934322/5687958/f94b4b04-981f-11e4-8c61-5ddca14b98a8.gif)
