### ISSUE TITLE
Assemble Not Assembling

### ISSUE THREAD

**Issue by grayghostvisuals** [grayghostvisuals/transformicons#61]
@doowb
Assemble is totally breaking my man. [http://cl.ly/image/1c0R370m3J3w](http://cl.ly/image/1c0R370m3J3w) What can we do to fix this? Here's the output during the npm install as well [http://www.codeshare.io/ycV1B](http://www.codeshare.io/ycV1B)

Basically the templates folder is copying itself into my site folder which should be the compiled HTML not the .hbs files.

**Comment by doowb** [comment]
Damn... I made a change earlier to fix another bug that's causing this. I'll have a fix soon.

**Comment by doowb** [comment]
All better now.

**Comment by grayghostvisuals** [comment]
@doowb Is there anything in place to catch these types of things from leaking out?

**Comment by doowb** [comment]
I added a test for this case in the module that needed updating. Until we get assemble 0.6.0 published to npm and use semver, this is the best I can do. This was a little unique because we're trying to allow you to update the `path` in either the pipeline (using `gulp-extname`) or inside assemble middleware. To do that we need to make sure it all gets sync'd up before writing the file out. All the other properties are connected by a reference so when one updates the other changes so we don't have to worry about syncing manually.

I hadn't run this update in a project where it would have been caught, otherwise I would have found it first.

**Comment by grayghostvisuals** [comment]
Understandable I get. Thanks for the help on the quick fix.
